CREATE TABLE [dbo].[Alugueis]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
	[Id_Cliente] INT NOT NULL FOREIGN KEY REFERENCES Clientes(Id),
	[Id_Filme] INT NOT NULL FOREIGN KEY REFERENCES Filmes(Id),
	[DATA_Aluguel] DATETIME DEFAULT GETUTCDATE()
)
